### PR TITLE
appdata: Improved description + added missing information

### PR DESCRIPTION
**Pull request by dsboger**

### CODE REVIEW

**Comment by dsboger** [comment]
I tried to improve FMIT description in fmit.appdata.xml. Please, check to see if I mentioned anything inaccurate and also if you like it, of course!

**Comment by gillesdegottex** [comment]
Thayks a lot. Most of it looks great to me.
Only one thing: "Free Musical Instrument Tuner (FMIT)" should appear somewhere as it is the definition of the acronym FMIT. I know this name s&%$ks as it is way too general, but I chose it 14 years ago (!) and I can't change it anymore.

**Comment by gillesdegottex** [comment]
(the PR check with travis is almost working properly know, without confusion with standard built. Only a bug in the automatic packaging make it fail)

**Comment by gillesdegottex** [comment]
Many tooltips have been erased in the process, would you mind checking this ?

**Comment by dsboger** [comment]
This PR does not deal with tooltips, but #96 replaces static tooltips mentioning anglo-saxon note names (e.g. A4) with dynamic ones using the localized note names setting (e.g. La4).

**Pull request merged**
