### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by gillesdegottex** [comment]
Just to check: Can we merge translation from both PRs and Weblate ? (@dsboger )

**Comment by trebmuh** [comment]
arf, I forgot that we have a weblate now!
don't worry, I'll do it on weblate.

**Comment by trebmuh** [comment]
Done.

**Comment by dsboger** [comment]
Strangely, somehow your latest Weblate translations did not get pushed to GitHub. Usually it is very quick with that. Maybe there is some issue?

**Comment by gillesdegottex** [comment]
Could you open an issue to keep track of this?

**Pull request closed without merging**
